name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: nuxt_laravel_todo
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1048
        ports:
          - 5432:5432
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Navigate to Backend Directory
        run: cd backend

      - name: Build Backend Docker Image
        run: |
          docker build -f Dockerfile -t backend-image .

      - name: Run Docker Container for Backend
        run: |
          docker run -d --name backend-container backend-image

      - name: Run Migrations
        run: |
          docker exec backend-container php artisan migrate

  frontend:
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Navigate to Frontend Directory
        run: cd frontend

      - name: Build Frontend Docker Image
        run: |
          docker build -f Dockerfile -t frontend-image .

      - name: Run Frontend Container
        run: |
          docker run -d -p 3000:3000 --name frontend-container frontend-image

      - name: Build Nuxt.js for Production
        run: |
          docker exec frontend-container npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          folder: .output/public
