name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main

jobs:
  # Backend job for building and testing Laravel with PostgreSQL
  backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: nuxt_laravel_todo
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1048
        ports:
          - 5432:5432
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo apt-get install -y docker-compose

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Test Backend with Docker
        run: |
          docker-compose up -d --build
          docker-compose exec -T app php artisan migrate

  # Frontend job for deploying Nuxt.js to GitHub Pages
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          npm install

      - name: Build Nuxt.js for Production
        run: |
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          folder: dist
