name: Laravel & Nuxt CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - backend/**
      - frontend/**
  pull_request:
    branches:
      - main
    paths:
      - backend/**
      - frontend/**

jobs:
  backend-deploy:
    runs-on: ubuntu-latest
    if: github.event.head_commit.modified != null && contains(github.event.head_commit.modified, 'backend')
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: nuxt_laravel_todo
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1048
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-timeout=30s
          --health-start-period=10s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Laravel Docker image
        run: |
          docker-compose -f docker-compose.yml build app

      - name: Run Laravel Tests
        run: |
          docker-compose exec -T laravel-app php artisan test

      - name: Deploy Laravel (if successful)
        if: success()
        run: |
          # Your deployment commands for Laravel backend here

      - name: Clean up Docker Compose
        run: |
          docker-compose -f docker-compose.yml down

  # frontend-deploy:
  #   runs-on: ubuntu-latest
  #   if: github.event.head_commit.modified != null && contains(github.event.head_commit.modified, 'frontend')
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '22'

  #     - name: Install dependencies for Nuxt
  #       run: |
  #         cd frontend
  #         npm install

  #     - name: Build Nuxt app
  #       run: |
  #         cd frontend
  #         npm run generate # Use 'npm run build' for production

  #     - name: Deploy Nuxt (GitHub Pages or other)
  #       if: success()
  #       run: |
  #         cd frontend
  #         git config --global user.name 'Your Name'
  #         git config --global user.email 'your-email@example.com'
  #         git checkout --orphan gh-pages
  #         git reset --hard
  #         git add .
  #         git commit -m "Deploy Nuxt.js to GitHub Pages"
  #         git push --force origin gh-pages

  #     - name: Clean up
  #       run: |
  #         cd frontend
  #         rm -rf .nuxt

