name: Deploy Backend

on:
  push:
    branches:
      - main
    # paths:
    #   - "backend/**"
    

jobs:
  deploy_laravel:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.32.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify installation

      - name: Build Laravel Docker container
        run: |
          docker-compose -f backend/docker-compose.yml build
          docker-compose -f backend/docker-compose.yml up -d
